### ISSUE TITLE
Add wildcard support for images

### ISSUE THREAD

**Issue by JordanSussman** [JordanSussman/drone-validator#1]
The operator may want to use some configurations like:

Allow all images within the `registry.company.com/drone-plugins/` namespace to utilize the secret:

```yml
secrets:
  secret/data/docker/username:
    - registry.company.com/drone-plugins/*
```

or

Allow all tags of the `registry.company.com/drone-plugins/npm` image to utilize the secret:

```yml
secrets:
  secret/data/docker/username:
    - registry.company.com/drone-plugins/npm:*
```
